blacklist = ["scratch"]

[default_session]
preview_command = "eza --all --oneline --git-ignore --color=always {}"

[[session]]
name = "s:home"
path = "~"

[[session]]
name = "s:agenda"
path = "~/Compendium/Agenda"
startup_command = "nvim -c ':Telescope find_files'; tmux kill-session"

[[session]]
name = "s:library"
path = "~/Compendium/Library"
startup_command = "yazi"

[[session]]
name = "s:slipbox"
path = "~/Compendium/Slipbox"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "s:notebook"
path = "~/Compendium/Notebook"
startup_command = "yazi"

[[session]]
name = "s:workspace"
path = "~/Compendium/Workspace"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "s:screenshots"
path = "~/Pictures/Screenshots"
startup_command = "yazi"

[[session]]
name = "s:downloads"
path = "~/Downloads"

[[session]]
name = "s:dotfiles"
path = "~/.dotfiles"
startup_command = "lazygit"

[[session]]
name = "s:src"
path = "~/.local/src"
startup_command='SEL="$(find . -mindepth 2 -maxdepth 2 -type d -printf "%P\n" | tee >(xargs -r zoxide add) | fzf)" && [ -n "$SEL" ] && tmux rename-session "$SEL" && cd "$SEL"'

[[session]]
name = "s:config"
path = "~/.dotfiles/.config"

[[session]]
name = "s:local/share"
path = "~/.dotfiles/.local/share"

[[session]]
name = "s:local/share/dwm"
path = "~/.dotfiles/.local/share/dwm"
startup_command = "nvim config.h"

[[session]]
name = "s:local/share/dwmblocks"
path = "~/.dotfiles/.local/share/dwmblocks"
startup_command = "nvim blocks.h"

[[session]]
name = "s:local/share/dmenu"
path = "~/.dotfiles/.local/share/dmenu"
startup_command = "nvim config.h"

[[session]]
name = "s:local/share/st"
path = "~/.dotfiles/.local/share/st"
startup_command = "nvim config.h"

[[session]]
name = "s:local/share/slock"
path = "~/.dotfiles/.local/share/slock"
startup_command = "nvim config.h"

[[session]]
name = "s:config/tmux"
path = "~/.dotfiles/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "s:config/sesh"
path = "~/.dotfiles/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "s:config/nvim"
path = "~/.dotfiles/.config/nvim"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "s:scratchpad"
path = "~"
