blacklist = ["scratch"]

[default_session]
preview_command = "eza --all --oneline --git-ignore --color=always {}"

[[session]]
name = "home"
path = "~"

[[session]]
name = "agim"
path = "~/Compendium/Agenda"
startup_command = "nvim -c ':Telescope find_files'; tmux kill-session"

[[session]]
name = "slipbox"
path = "~/Compendium/Slipbox"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "workspace"
path = "~/Compendium/Workspace"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "dotfiles"
path = "~/.dotfiles"

[[session]]
name = "scripts"
path = "~/.dotfiles/.local/scripts"

[[session]]
name = "autostart"
path = "~/.dotfiles/.local/share"
startup_command="nvim autostart.sh"

[[session]]
name = "tmp"
path = "/tmp"
startup_command='printf "Folder name: " && read dir && mkdir -p -- "$dir" && cd -- "$dir" && tmux rename-session -- "$PWD"'

[[session]]
name = "src"
path = "~/.local/src"
startup_command="~/.local/scripts/tmux-picker.sh"

[[session]]
name = "share"
path = "~/.dotfiles/.local/share"
startup_command="~/.local/scripts/tmux-picker.sh 1 share/"

[[session]]
name = "config"
path = "~/.dotfiles/.config"
startup_command="~/.local/scripts/tmux-picker.sh 1 config/"
