blacklist = ["scratch"]

[default_session]
preview_command = "eza --all --oneline --git-ignore --color=always {}"

[[session]]
name = "home"
path = "~"

[[session]]
name = "agenda"
path = "~/Compendium/Agenda"
startup_command = "nvim -c ':Telescope find_files'; tmux kill-session"

[[session]]
name = "library"
path = "~/Compendium/Library"
startup_command = "yazi"

[[session]]
name = "slipbox"
path = "~/Compendium/Slipbox"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "notebook"
path = "~/Compendium/Notebook"
startup_command = "yazi"

[[session]]
name = "workspace"
path = "~/Compendium/Workspace"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "screenshots"
path = "~/PictureScreenshots"
startup_command = "yazi"

[[session]]
name = "downloads"
path = "~/Downloads"

[[session]]
name = "dotfiles"
path = "~/.dotfiles"
startup_command = "lazygit"

[[session]]
name = "src"
path = "~/.local/src"
startup_command='SEL="$(find . -mindepth 2 -maxdepth 2 -type d -printf "%P\n" | tee >(xargs -r zoxide add) | fzf)" && [ -n "$SEL" ] && tmux rename-session "$SEL" && cd "$SEL"'

[[session]]
name = "config"
path = "~/.dotfiles/.config"

[[session]]
name = "local/share"
path = "~/.dotfiles/.local/share"

[[session]]
name = "local/share/dwm"
path = "~/.dotfiles/.local/share/dwm"
startup_command = "nvim config.h"

[[session]]
name = "local/share/dwmblocks"
path = "~/.dotfiles/.local/share/dwmblocks"
startup_command = "nvim blocks.h"

[[session]]
name = "local/share/dmenu"
path = "~/.dotfiles/.local/share/dmenu"
startup_command = "nvim config.h"

[[session]]
name = "local/share/st"
path = "~/.dotfiles/.local/share/st"
startup_command = "nvim config.h"

[[session]]
name = "local/share/slock"
path = "~/.dotfiles/.local/share/slock"
startup_command = "nvim config.h"

[[session]]
name = "config/tmux"
path = "~/.dotfiles/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "config/sesh"
path = "~/.dotfiles/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "config/nvim"
path = "~/.dotfiles/.config/nvim"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "scratchpad"
path = "~"
