blacklist = ["scratch"]

[default_session]
preview_command = "eza --all --oneline --git-ignore --color=always {}"

[[session]]
name = "home"
path = "~"

[[session]]
name = "agim"
path = "~/Compendium/Agenda"
startup_command = "nvim -c ':Telescope find_files'; tmux kill-session"

[[session]]
name = "slipbox"
path = "~/Compendium/Slipbox"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "workspace"
path = "~/Compendium/Workspace"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "dotfiles"
path = "~/.dotfiles"

[[session]]
name = "src"
path = "~/.local/src"
startup_command='SEL="$(find . -mindepth 2 -maxdepth 2 -type d -printf "%P\n" | tee >(xargs -r zoxide add) | fzf)" && [ -n "$SEL" ] && tmux rename-session "$SEL" && cd "$SEL" && clear'

[[session]]
name = "scripts"
path = "~/.dotfiles/.local/scripts"

[[session]]
name = "autostart"
path = "~/.dotfiles/.local/share"
startup_command="nvim autostart.sh"

[[session]]
name = "share"
path = "~/.dotfiles/.local/share"
startup_command='SEL="$(find . -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | tee >(xargs -r zoxide add) | fzf)" && [ -n "$SEL" ] && tmux rename-session "share/$SEL" && cd "$SEL" && clear&& nvim -c ":Telescope find_files"'

[[session]]
name = "config"
path = "~/.dotfiles/.config"
startup_command='SEL="$(find . -mindepth 1 -maxdepth 1 -type d -printf "%P\n" | tee >(xargs -r zoxide add) | fzf)" && [ -n "$SEL" ] && tmux rename-session "config/$SEL" && cd "$SEL" && clear && nvim -c ":Telescope find_files"'
