[[mgr.prepend_keymap]]
# https://github.com/mwh/dragon
# run = '''shell 'dragon --and-exit --on-top "$@"' --confirm'''
on = "<C-i>"
run = '''
	shell 'dragon -x -i -T "$1"' --confirm
'''
desc = "Drag file(s) with dragon"

[[mgr.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell in the current directory"
