[mgr]
ratio = [0, 4, 2]

[preview]
cache_dir = "~/.cache/yazi"

[opener]
edit = [
	{ run = 'nvim "$@" || vi "$@"', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'code %*', orphan = true, desc = "code", for = "windows" },
	{ run = 'code -w %*', block = true,  desc = "code (block)", for = "windows" },
]

open = [
	{ run = 'devour xdg-open "$@"', block = false, for = "unix" }
]

play = [
	{ run = 'devour mpv "$@"', block = false, for = "unix" }
]

[open]
prepend_rules = [
	{ mime = "video/*", use = "play" },
]
