general.import = [
  "~/.config/alacritty/theme.toml"
]


[font]
size = 12.0

normal = { family = "monospace", style = "Regular" }
bold = { family = "monospace", style = "Bold" }
italic = { family = "monospace", style = "Italic" }
bold_italic = { family = "monospace", style = "Bold Italic" }

offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

builtin_box_drawing = true

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true

[keyboard]
bindings = [
  { key = "Plus",  mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control",       action = "DecreaseFontSize" },
  { key = "Key0",  mods = "Control",       action = "ResetFontSize" }
]

[cursor]
style = { shape = "Block", blinking = "Off" }
